// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNpGStmitGL-SNDLupnLrgsfQLTgl5M7M',
    appId: '1:1080463414374:web:b2fb4993b599e0d413c9a7',
    messagingSenderId: '1080463414374',
    projectId: 'commissions-87201',
    authDomain: 'commissions-87201.firebaseapp.com',
    storageBucket: 'commissions-87201.firebasestorage.app',
    measurementId: 'G-CQLD2WDFGB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzQ6pJ8DbqpeetyhhlWCNuOvXdsgaWNsU',
    appId: '1:1080463414374:android:1d43157bb2f8988213c9a7',
    messagingSenderId: '1080463414374',
    projectId: 'commissions-87201',
    storageBucket: 'commissions-87201.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAheTMYEUcQk4UIcPsFG9OazHKubRCCO-4',
    appId: '1:1080463414374:ios:76b0431af2da15f913c9a7',
    messagingSenderId: '1080463414374',
    projectId: 'commissions-87201',
    storageBucket: 'commissions-87201.firebasestorage.app',
    iosBundleId: 'com.example.bookwell',
  );
}
